### ISSUE TITLE
pom.xml & Jenkinsfile issues

### ISSUE THREAD

**Issue by svandenhoek** [molgenis/molgenis-app-gavin2#12]
Given links are from commit `bc97059ea103bef22c4e07ec5ff2dad584985ffe`, which is the most recent commit in `master` as of writing this issue.

### pom.xml
- The given [scm information](https://github.com/molgenis/molgenis-app-gavin2/blob/bc97059ea103bef22c4e07ec5ff2dad584985ffe/pom.xml#L29) refers to the molgenis repository instead of this one.
- Coverage information seems to be missing in [pull-requests](https://github.com/molgenis/molgenis-app-gavin2/pull/4#issuecomment-589640002).
- `<issueManagement>` information is missing.

### Jenkinsfile
- Multiple occurences can be found mentioning a [junit step](https://github.com/molgenis/molgenis-app-gavin2/blob/bc97059ea103bef22c4e07ec5ff2dad584985ffe/Jenkinsfile#L53), while TestNG seems to be used in many (if not all?) tests.

**Comment by dennishendriksen** [comment]
Jenkinsfile issues resolved in https://github.com/molgenis/molgenis-app-capice/pull/18
